- name: "Configuring firewall for master node"
  firewalld: 
    port: "{{ item }}/tcp"
    permanent: "true"
    state: enabled
    immediate: "true"
  with_items:
    - 6443
    - 2379-2380
    - 10250-10255

- name: "Initializing Kubernetes Master Node"
  shell: "source ~/.bashrc && kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ private_ip|quote }}" 
  register: out
  args:
    executable: /bin/bash
    creates: /etc/kubernetes/admin.conf

- name: "printing stdout for debug"
  when: verbose
  debug:
    var: out.stdout_lines

- name: "printing stderr for debug"
  when: verbose
  debug:
    var: out.stderr_lines


- name: "Configuring Kubectl for normal user"
  file: 
    path: "/home/{{ normal_user }}/.kube"
    state: directory
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"
    mode: 0775

- name: "copy-kubeconfig"
  shell: "cp /etc/kubernetes/admin.conf /home/{{ normal_user }}/.kube/config"
  args:
    creates: "/home/{{ normal_user }}/.kube/config"

- name: "config-permission"
  file: 
    path: "/home/{{ normal_user }}/.kube/config"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"
    mode: 0600

- name: "Installing container overlay network"
  become: yes
  become_user: "{{ normal_user }}"
  shell: "source ~/.bashrc && kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml && touch ~/done"
  args:
    executable: /bin/bash
    creates: "~/done"

- name: sleep for 20 sec and continue with play
  wait_for: 
    timeout: "20"
  delegate_to: localhost

- name: "Waiting for deployments to be completed"
  become: yes
  become_user: "{{ normal_user }}"
  script: ../files/wait-for-deployment.sh

- name: "Getting Kubeadm join command from master node"
  shell: "kubeadm token create --print-join-command"
  register: kubeadm-join-command
