- name: "Configuring firewall for slave node"
  firewalld: 
    port: "{{ item }}/tcp"
    permanent: "true"
    state: enabled
    immediate: "true"
  with_items:
    - 10250
    - 10255
    - 30000-32767

- name: "Joining slave nodes"
  shell: "{{ hostvars['master01']['kubeadm-join-command']['stdout'] }}"
  register: out

- name: "printing stdout for debug"
  when: verbose
  debug:
    var: out.stdout_lines

- name: "printing stderr for debug"
  when: verbose
  debug:
    var: out.stderr_lines